
services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n  # ✅ This line loads your saved workflows
      - ../certs:/certs
    env_file:
      - ./n8n.env
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=yourpassword
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - SSL_KEY=/certs/key.pem
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - SSL_CERT=/certs/cert.pem

volumes:
  n8n_data:
    external: true

